_BASE_: "../COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml"
MODEL:
  WEIGHTS: "detectron2://COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x/137849621/model_final_a6e10b.pkl"
DATASETS:
  TEST: ("keypoints_coco_2017_val_100",)
TEST:
  EXPECTED_RESULTS: [["bbox", "AP", 52.47, 0.02], ["keypoints", "AP", 67.36, 0.02]]
