_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "PanopticFPN"
  MASK_ON: True
  SEM_SEG_HEAD:
    LOSS_WEIGHT: 0.5
DATASETS:
  TRAIN: ("coco_2017_train_panoptic_separated",)
  TEST: ("coco_2017_val_panoptic_separated",)
