_BASE_: "Base-DensePose-RCNN-FPN-Human.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_DENSEPOSE_HEAD:
    NAME: "DensePoseDeepLabHead"
    CSE:
      EMBED_LOSS_NAME: "SoftEmbeddingLoss"
SOLVER:
  MAX_ITER: 130000
  STEPS: (100000, 120000)
