_BASE_: "Base-DensePose-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_DENSEPOSE_HEAD:
    UV_CONFIDENCE:
      ENABLED: True
    DECODER_ON: True
    LOSS_NAME: "DensePoseChartLoss"
    PREDICTOR_NAME: "DensePoseChartPredictor"
  SEMI:
    TEACHER_WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
SOLVER:
#  CLIP_GRADIENTS:
#    ENABLED: True
#  WARMUP_FACTOR: 0.025
  MAX_ITER: 260000
  STEPS: (230000, 250000)
#SOLVER:
#  MAX_ITER: 130000
#  STEPS: (100000, 120000)
