_BASE_: "Base-DensePose-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_DENSEPOSE_HEAD:
    DECODER_ON: True
  SEMI:
    TEACHER_WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
    COR:
      CRT_ON: True
      WARM_ITER: 60000
SOLVER:
  MAX_ITER: 180000
  STEPS: (120000, 160000)
#SOLVER:
#  MAX_ITER: 130000
#  STEPS: (100000, 120000)
