MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_vgg_backbone"
  VGG:
    DEPTH: 16
  ANCHOR_GENERATOR:
    SIZES: [[128, 256, 512]]
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
    IN_FEATURES: ['vgg_block5']
  ROI_HEADS:
    NAME: "VggROIHeads"
    IN_FEATURES: ['vgg_block5']
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    POOLER_RESOLUTION: 7
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
