_BASE_: "Base-DensePose-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  ROI_DENSEPOSE_HEAD:
    NAME: "DensePoseV1ConvXHead"
    CSE:
      EMBED_LOSS_NAME: "SoftEmbeddingLoss"
SOLVER:
  MAX_ITER: 130000
  STEPS: (100000, 120000)
